apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana
  labels:
    name: {{ .Release.Name }}-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-grafana
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-grafana
    spec:
      securityContext:
        fsGroup: 472
      containers:
        - name: grafana
          image: {{ .Values.Grafana.image | default "grafana/grafana:latest" }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.Grafana.username }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.Grafana.password }}
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "true" # Example of another environment variable
            - name: GF_SERVER_HTTP_PORT
              value: "3000" # Example of setting the Grafana port explicitly
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-grafana-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-grafana-pvc
  labels:
    app: {{ .Release.Name }}-grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.Grafana.persistence.size | default "2Gi" }}
  storageClassName: {{ .Values.Grafana.persistence.storageClassName | default "Standard" }}
