apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-influxdb
  labels:
    app: {{ .Release.Name }}-influxdb
spec:
  type: {{ .Values.InfluxDB.service.type | default "ClusterIP" }} # Allows flexibility for service type (ClusterIP, NodePort, LoadBalancer)
  ports:
    - port: 8086
      targetPort: 8086 # Target container port
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-influxdb # Matches the selector in the Deployment