apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jmeter-worker
  labels:
    app: {{ .Release.Name }}-jmeter-worker
spec:
  clusterIP: None  # Required for headless service
  selector:
    app: {{ .Release.Name }}-jmeter-worker
  ports:
    - name: rmi
      port: 1099
      targetPort: 1099
      protocol: TCP
    - name: communication
      port: 60000
      targetPort: 60000
      protocol: TCP