apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jmeter-vts
  labels:
    app: {{ .Release.Name }}-jmeter-vts
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}-jmeter-vts
  type: "ClusterIP"
